config/routes.rb
Rails.application.routes.draw do
  resources :iwork
  get 'iwork/index'
  match 'index', to: 'iwork#index', via: [:post, :get]
  get 'iwork/formularz'
  get 'iwork/view'
  match 'formularz', to: 'iwork#formularz', via: [:post, :get]
  match 'view', to: 'iwork#view', via: [:post, :get]
  match 'iwork/utworz' => 'iwork#utworz', via: [:get, :post]
  match 'iwork/pokaz' => 'iwork#pokaz', via: [:get, :post]

  root 'iwork#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/iwork_controller.rb
class IworkController < ApplicationController

  def index

  end



  def formularz
  end

  def view

  end

  def utworz
  end
  end
  def parametryrej
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/iwork/formularz.html.erb
<div class="row fullscreen">
  <div class="col s12 m6 l6 table">
    <div class="tablecell">
      <div class="row">
        <form class="col s12">
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input id="email" type="email" class="validate">
              <label for="email">Email</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input id="password" type="password" class="validate">
              <label for="password">Password</label>
              <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col s12 m6 l6 table">
    <div class="tablecell">
      <div class="row">
        <form class="col s12">
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input type="text">
              <label for="imie">Imie</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input type="text">
              <label for="nazwisko">Nazwisko</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input type="text">
              <label for="email">Email</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <input type="text">
              <label for="password">Password</label>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/iwork/index.html.erb
	<div class="row" style="margin-top: 20px">
		<div class="col s12 m4 l4 center-align">
			<!-- <img style="height: 200px" class=" responsive-img" src="https://cdn3.iconfinder.com/data/icons/work-4/154/office-work-tie-round-form-512.png"> -->
      <div class="center promo promo-example">
         <i class="material-icons large">stay_current_portrait</i>
         <p class="promo-caption">Kontakt</p> 
          <p class="light center">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.</p>
<a class="waves-effect waves-light btn-large"><i class="material-icons left">cloud</i>button</a>
      </div>
      



		</div>
		<div class="col s12 m4 l4 center-align">
			<!-- <img style="height: 200px" class=" responsive-img" src="https://cdn1.iconfinder.com/data/icons/mix-color-3/502/Untitled-35-512.png"> -->
         <i class="material-icons large">stay_current_portrait</i>
         <p class="promo-caption">Kontakt</p> 
          <p class="light center">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.</p>
      


<a class="waves-effect waves-light btn-large"><i class="material-icons left">cloud</i>button</a>
		</div>
		<div class="col s12 m4 l4 center-align">
			<!-- <img style="height: 200px" class=" responsive-img" src="https://cdn0.iconfinder.com/data/icons/creative-business-and-development/512/office_desk_lamp_workplace_studio_working_table_business_work_flat_design_icon-512.png"> -->
         <i class="material-icons large">stay_current_portrait</i>
         <p class="promo-caption">Kontakt</p> 
          <p class="light center">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.</p>
      


<a class="waves-effect waves-light btn-large"><i class="material-icons left">cloud</i>button</a>
		</div>

	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iwork</title>
  <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


</head>
<body>


<nav>

  <div class="nav-wrapper">
    <a href="index.html" class="brand-logo">Logo</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down black-text"><span class="black-text">
        <li><%= link_to "Strona głównat", index_path %></li>
        <li><%= link_to "Oferty", index_path %></li>
        <li><%= link_to "Kontakt", index_path %></li>
    <li><%= link_to "Logowanie / rejestracja", formularz_path %></li>
    </span>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="index.html">Strona główna</a></li>
      <li><a href="index.html">Oferty</a></li>
      <li><a href="collapsible.html">Kontakt</a></li>

    </ul>
  </div>
</nav>


<%= yield %>


</body>
</html>